name: 🚀 FINAL DEPLOYMENT (DONE)
on:
  push:
    branches:
      - main

jobs:
  web-deploy:
    name: 🎉 Success Sync
    runs-on: ubuntu-latest
    
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v3

      - name: 🟢 Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: 🐘 Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'

      - name: 🏗️ Build Assets (Vite)
        run: |
          npm install
          npm run build

      - name: 📂 Sync to cPanel
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./
          # Karena FTP sudah dikunci ke panelapk, maka kita pakai /
          server-dir: /
          exclude: |
            **/.git*
            **/.git*/**
            **/node_modules/**
            **/vendor/**
            **/tests/**
            **/storage/logs/*
            **/storage/framework/cache/*
            **/storage/framework/sessions/*
            **/storage/framework/views/*
            .env
            composer.zip
            deploy.zip
            public/extract.php
            public/identitas.php
            rencanaapkexampanel.md
